output_dir: "outputs/test1"

model_name: "all-MiniLM-L6-v2"
train_data: "data/IMPPRES/presupposition/change_of_state.jsonl"
trigger_type: "change_of_state"

hyper_params:
  seed: 42

  num_epochs: 50
  num_warmup_steps: 0
  early_stopping: 10

  train_batch_size: 32
  dev_batch_size: 64

  loss_function: "contrastive"
  learning_rate: 1e-3
  lr_gamma: 0.90

wandb:
  send_to_wandb: True
  wandb_project: "pres_lens"
  wandb_run_name: "test1"

debug:
  data_size_percentage: 100
